name: Deploy Frontend to Dev

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Build Angular (dv)
        run: npx ng build --configuration=dv

      - name: Deploy por FTP (limpia chunks viejos)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir: ./dist/notasCreditos-front/browser/
          server-dir: /public_html/tc/frontend/
          dangerous-clean-slate: true